### ISSUE TITLE
Improve dealing with the output of the RANSAC plugin

### ISSUE THREAD

**Issue by ao2** [cloudcompare/trunk#211]
Hi,

we are using CloudCompare in our work-flow for structural analysis on point clouds captured with a laser scanner.

Basically this is what we do:

1. We apply the RANSAC plugin to find planes
2. We **manually** select all the sub-clouds representing planes created by the RANSAC plugin
3. We convert the sub-clouds to mesh: Edit->Mesh->Delaunay 2.5D (XY plane)
4. We merge all the meshes
5. We export the mesh as "ASCII cloud" for post-processing

The most tedious work is step 2, to expand and select all the planes sub-clouds **manually**.

Can this be improved?

I thought that an easy solution would be to have a "Select by type" tool, what do you think?

Alternatively the RANSAC plugin can be improved to output a mesh directly, but this is a less general solution.

Are you willing to add this feature yourself, or at least to provide some help if I am going to do the coding part?

Thanks,
   Antonio

**Comment by cloudcompare** [comment]
Interesting suggestion. I would gladly guide you so that you can implement it.

I only have one concern: I believe the qRansac plugin outputs each cloud subsets corresponding to each primitive, then each cloud has the corresponding primitive as child, and those primitives also have a cloud as child (their vertices). So if you select all 'clouds' for instance, you'll get the subsets AND the primitives vertices...

As you'll need a small dialog to let the user choose the entity type to 'select', you could add an additional checkbox to let you specify whether you want to do a full recursion or only get the 'first' cloud in each branch.

**Comment by ao2** [comment]
I am proficient in C, and I can do C++, but I have no experience with Qt and I don't know the CloudCompare codebase either, so as a first step we could decide where to put such tool in the UI and you can suggest what the files to modify are.

Then I'll make a prototype patch which selects by type/label hardcoding the type or the label, and then we can decide how to proceed from there (i.e. if you want to pick it up yourself of if I will finish the implementation).

**Comment by cloudcompare** [comment]
Indeed, I think we should add this functionality to the DB tree context menu (it appears when the user right clicks on a DB item).

You can see how it works in https://github.com/cloudcompare/trunk/blob/master/qCC/db_tree/ccDBRoot.cpp (see how we use the 'm_sortSiblingsType' action - which corresponds to the context menu entry 'Sort siblings by type').

Create your own action and add it to the context menu when a group is selected (or when an entity with at least one or two children for instance). This action associated 'slot' will display a drop down menu with either all possible types, or better all the types that are available among the siblings of the selected item. You can use the ccPickOneElementDlg widget to do this easily.

Eventually you can create the list of items to select and actually 'select' them (you should use one of the ccDBRoot::selectEntities methods).

I'm sorry that I can't do it myself (it would be faster) but I'm really running out of time.

**Comment by ao2** [comment]
@cloudcompare thanks for the hints.

I have a prototype implementation here: https://gist.github.com/ao2/62383c6d46f2e33eab65
This may even be enough for our use case but it's not generic enough for inclusion in CloudCompare I guess.

Before working on the UI for picking up the selection criteria I would like to clean up the back-end selection function, some ideas are also in the comments in the diff from above.

Basically we could:
* add a generalization of ```ccHObject::filterChildren()``` (possibly with a new name ```filterChildrenByTypeAndName```?) which allows restricting the filtering using the entity name
* optionally allowing such restriction criterion to match either the exact name or a prefix
* use such a function in selectChildrenByTypeAndName()

But if you find the current version acceptable just say so :)

Thanks,
   Antonio

**Comment by cloudcompare** [comment]
Interesting, thanks.

But as you have guessed, this is a bit too particular to be used in the standard version of CC. We should stick to more generic entries in the context menu (e.g. 'Select by type' and 'Select by type and/or name'). Those methods would typically spawn a dialog (I'll create it if you prefer). Meanwhile for the prototype you can use the ccPickOneElementDlg dialog to pick the type (just a few types would do for the prototype) and QInputDialog::getText tool to get the name for instance.

Then we can do as you suggest. It's not necessary to create a new 'filterChildren' method though. You could simply use 'filterChildren' and add a second pass on the result to test for the names. I'll let you choose how you prefer to do this.

Otherwise:
- you should use QString by default instead of char* or std::string. This is the default string type in CC and it's much more powerful than the other types (especially regarding local characters). You'll be particularly interested by the various methods to compare strings such as 'startsWith' and 'contains' (this latter accepts regular expressions notably).
- you shouldn't select entities one by one but use the 'selectEntities' method instead (it's much faster - the first version would take ages if you have hundreds of children).

**Comment by ao2** [comment]
I kept it simple and just added a second pass to restrict the filtered children by name.

The dialogs are very primitive for now, in the Type and Name search I show two separate dialogues one after the other which is just awful :).

I think that in the final version just one dialog and one menu entry is enough "Select by type and/or name" and then if the name is empty only the type is matched.

If you could create the dialog for me it would be great, I imagine it something like that:
```
"Choose an object type and optionally a name" (static label, help text)
Object type: [ Mesh ...] (drop down menu)
Object name: [ ______ ] (text area)
[x] use regex (checkbox)
```

Here is the latest prototype, the search function should work a lot better now, thanks for the suggestions: https://gist.github.com/ao2/62383c6d46f2e33eab65/4d50018cee4dfccec6ae3c65e5ce0cf879496108#file-cloudcompare-select-entities_v2-diff

**Comment by cloudcompare** [comment]
That looks good. I'll add the dialog, no problem.

Can you make a pull request maybe?

**Comment by ao2** [comment]
How do we want to coordinate?

Should I commit the whole patch and then you will remove code when adding the new dialog? Or should I commit only the ```selectChildrenByTypeAndName``` method and you'll add the UI part?

**Comment by cloudcompare** [comment]
You can commit the whole thing and I'll clean it afterwards.

**Comment by ao2** [comment]
Here is the patch with the commit message which can be applied with ```git am```:

https://gist.githubusercontent.com/ao2/62383c6d46f2e33eab65/raw/ac06f53de357f2d48a5c233758fab082c92c172c/0001-Add-a-mechanism-to-select-entities-by-type-and-then-.patch

**Comment by cloudcompare** [comment]
Okay, I've commited your patch and my changes on the CleanMeshCutter branch.

You can give it a try.

**Comment by ao2** [comment]
The dialog looks good, thanks.

There are still some minor issues:
* I found out that selecting Meshes is still a little weird for instance: some parent elements get selected too;
* the menu entry says "siblings" while I think it should say "children".

I'll look into those issues and follow up in the next days.

BTW I would have expected to see my patch committed verbatim ad then the improvements on top of it as separate commits, that would have been more git-like and my commit message would have been preserved (I take quite some time to write commit messages, I find it kind of a waste when they are thrown away :wink:), also my name would have shown up directly in the git project history as an author.

Anyway I see that you mentioned me in the commit message, so we are good for this time.

**Comment by cloudcompare** [comment]
Huh, this is why I suggested you to do a 'Pull request' ;). This is how it works with github...

When I applied your patch, I lost your comments (I use SmartGit and I almost never use patches). This is why I had to manually add your name to my own commit.

For the issues, I can fix them as well. If you do it yourself, please make a pull request so that there will be no issue ;)

**Comment by ao2** [comment]
I see, I only use git from the command line, and so dealing with patches using ```git format-patch``` and ```git am``` is the most natural and lightweight way for me to move changes preserving all the related information.

Apparently SmartGit doesn't know how to correctly apply a proper patch created with ```git format-patch``` which is one of the basic git commands; well, I'll consider forks and pull-requests next time, no time to complain "too much" :smile:

**Comment by ao2** [comment]
Here is the pull request: https://github.com/cloudcompare/trunk/pull/212

I also thought that the "select children" functionality could be enabled even when ```selCount >=1``` to allow using ctrlMode selection (e.g. I select something in a subtree and then want to add-select something else in an unrelated subtree), but I haven't still enforced this behavior, I wanted to know what you think first.

**Comment by cloudcompare** [comment]
Ok thanks for your contribution!
