### ISSUE TITLE
picked points labels get cleared when you try to pick more points

### ISSUE THREAD

**Issue by foobarbecue** [cloudcompare/trunk#220]
1. Pick some points with the "point list picking" tool
2. Edit their labels
3. Click the "point list picking" tool again

The original points remain, but their labels have been changed to "Point #0" etc. Easy to lose a lot of hard work this way.

Also, is there no way to export points with a column for their label?

**Comment by cloudcompare** [comment]
Indeed. It's because we want to make the labels name match the values in the 'label index' column (the left-most one). And when you change the 'start index', all labels change accordingly.

I changed this behavior a little so that an already existing label with a name that doesn't start by 'Point #' will keep its name.

And I also added an option to export the list as 'Label name, x, y, z'.

**Comment by foobarbecue** [comment]
Wow, from my point of view, you fixed this overnight! Brilliant, you made my day.

**Comment by dev741** [comment]
Hi, 
Can i Know please how to edit labels in CloudCompare?
