### ISSUE TITLE
Cloudcompare -> rasterize -> column with zeros

### ISSUE THREAD

**Issue by mjoaoh** [cloudcompare/trunk#221]
Hello

I have a perfectly regular point cloud that I got from a X Y Z file
![clipboard01](https://cloud.githubusercontent.com/assets/6091516/8545209/21ca7288-24a4-11e5-912a-914ccc615815.jpg)

When I Tools -> Projection -> rasterize -> Update grid 

appears a white column (=column with no data)

![clipboard02](https://cloud.githubusercontent.com/assets/6091516/8545240/6f4a00be-24a4-11e5-9ad0-02e326f43f4e.jpg)

I'm using verison 2.6.1 (W32 bits) but the last version had already this problem.

Need help. Thank you

Maria

**Comment by dgirardeau** [comment]
It may be more a sampling issue than an actual bug. It generally happens when the points are already organized in a regular manner (for instance parallel scanlines) and you use a grid step that is slightly different from the gap between each scanline (even a little bit different).

If you change the grid step of a small amount or if you shift the grid corner position, can you still see this white line?

Otherwise I'm interested in your cloud (and the parameters you use).

**Comment by mjoaoh** [comment]
You're right.

My grid came from a 3D scanner. It was a regular matrix. The grid I was generating had the same step than the original grid. 

I changed the step (from 0.5 to 0.500010) and the gap disapeared.

It a pitty that I can use the same step. It would be nice tool to transform a X Y Z very long file in a small height matrix file.

thak you

**Comment by mjoaoh** [comment]
(I have closed!)

**Comment by dgirardeau** [comment]
This is a classical 'signal processing' issue. I guess in this case that the numerical representation of the points is the culprit. What kind of files have you used to import the data? Can you increase the representation precision? (e.g. add more digits if you used an ascii file)

And you can also change the grid starting position if you want to keep the same step,

**Comment by mjoaoh** [comment]
usually I use "normal" point clouds. But, this time, I need to compare a point cloud of an object with a 3D scanning of that object.
