### ISSUE TITLE
Cross Section Command Line Not Working

### ISSUE THREAD

**Issue by m-cross** [cloudcompare/trunk#227]
I'm currently looking to develop a command line process for converting points clouds to several tiled meshes. Using CloudCompare 2.6.1 via command line I'm getting 'Unknown or misplaced command' when using CROSS_SECTION, my command line is as follows:

-O "D:\66000_84000_A_Filtered.las" -AUTO_SAVE OFF -DELAUNAY -CROSS_SECTION "D:\CC_Tile.xml" -M_EXPORT_FMT FBX -FBX_EXPORT_FMT FBX_binary -SAVE_MESHES

I also tried to replicate the results I'm looking for using the GUI and found that the cross section tool is disabled when a mesh is selected, the command line interface documentation suggests this tool should work on meshes as well as point clouds.

**Comment by cloudcompare** [comment]
The CROSS_SECTION option in command line, as well as the ability to use the Cross Section tool on meshes are features of the 2.6.2 version (the beta version is online for Windows 64 bits - otherwise you'll have to compile it yourself).

Moreover the original workflow was to load files from the 'FilePath' folder (contrarily to what was written in the documentation ;). I've changed it so that you can use the loaded clouds or meshes. You have to replace 'FilePath' by 'OutputFilePath' for this to work (see the updated example XML file online). And if you simply remove the 'FilePath' key, then the files will be saved next to the original files (still in subfolders though).

The online beta version is currently uploading.
