### ISSUE TITLE
Computing normals on FARO file not working as expected?

### ISSUE THREAD

**Issue by onitreb** [cloudcompare/trunk#388]
As these features and procedure change over time, maybe I'm doing it wrong.

Here is what worked well on version 2.63 (beta)
Import FARO project (.lsproj) to CC (yes, load RGB colors)
Select all scans and merge into one
Compute normals with these settings:
local surface model: quadric
neighbors: use octree (auto I think)
orientation: use scan grid

This resulted in good normals.

In 2.7 I am getting not-good normals. Inconsistant, some inverted

![untitled-1](https://cloud.githubusercontent.com/assets/2154479/15520591/fb42267c-21bb-11e6-9eaf-b6ff21e216f1.jpg)

Is there a different way to do normal calcs now? And it seems that normals can't be calculated from the scanner head locations, even though CC knows the scanner head locations?

**Comment by cloudcompare** [comment]
I'll test this on my side and I'll get back to you.

**Comment by cloudcompare** [comment]
I tested on my side and I can't reproduce the issue.

However as the automatic extraction of the radius is randomized, it's possible to get sometimes a too small value. In this case some points will have a black normals as CC couldn't get enough neighbors around them to compute the normals.

Can you check:
- that the 'auto' radius is stable (by clicking multiple times on the 'auto' button)
- try to increase the detected radius (X2 or X3) and see if it fixes the black parts

**Comment by onitreb** [comment]
The auto radius is not stable. It changes every time I click it. Hovering in the .003-.005 zone.

Using .1 I get black normals

**Comment by cloudcompare** [comment]
Oh it's not that 'unstable' (I mean the range is not that wide). But if the radius is a little bit too small it means that the density is quite varying in your cloud.

I'll try to increase the auto radius a little bit (even though the bigger the radius the longer the computation).

**Comment by onitreb** [comment]
Okay. Thanks.

Could you reiterate the most appropriate settings to get a good normal calculation for a FARO file/project? I can't figure out a good combination.

local surface: quadric?
neighbors: use octotree: what is a good range to try? .05?
orientation: use scan grid?

These settings leave me with a lot of normals flipped the wrong way.

**Comment by cloudcompare** [comment]
*Local surface*: it all depends on your cloud. If it has sharp corners and it's very clean, then you can use the 2.5D triangulation. But if it is very smooth or noisy you'd better take one of the others. The plane is faster and the quadric is better with high curvature surfaces.

*Neighbors*: I'd definitely suggest to use the octree. The result is much nicer... providing you find the right radius. The issue is that finding a good radius depends a lot on your cloud density. You have to find the radius that works for all points (or you have to be ready to remove the points with the lowest density).

*Orientation*: yes, always use the scan grids when available.

When you say that the normals are 'flipped the wrong way', are they actually good when you look at your cloud from behind or are they black whatever the camera direction? The latter means that there was not enough point to compute the normal and therefore it was set to (0, 0, 0). The only solution to cope with these points is either to increment the octree radius or to remove the lowest density points.

If however it was the first case (i.e. the normal really inverted) then I would be very interested to get a hand on your cloud!
