### ISSUE TITLE
change Windows.h to lowercase

### ISSUE THREAD

**Issue by maruncz** [cloudcompare/trunk#414]
hi

can you change all #include Windows.h to lowercase?

on windows it does not really matter but i am cross compiling and mingw has windows.h

here is disscusion about it https://github.com/mxe/mxe/issues/1437

**Comment by cloudcompare** [comment]
I guess it's possible.

Just in case: wouldn't it be easier to rename the 'windows.h' file or duplicate it (maybe in another default folder)?

**Comment by maruncz** [comment]
mingw uses lowercase 
on ntfs filesystem it does not matter but on linux does
and MSDN actually does not know correct way to write it - see that mxe issue above

i already made change in my fork of cloudcompare https://github.com/maruncz/cloudcompare/commit/63b1248afb4fae3035b30afbb887447aa6b433a5
and it works for me

**Comment by cloudcompare** [comment]
Yeah but if you work on Linux or any other OS that can handle both the 'windows.h' and 'Windows.h' files in the same folder, wouldn't it be easier to have to two versions of this file on your side? (with a simple copy).

But otherwise we can change all the "Windows.h" to "windows.h"... hoping it won't make another cross compilation / compiler tool fail ;)

**Comment by cloudcompare** [comment]
See 44a56fc0810c79a0a4c34445d8494d0c9756bca6

**Comment by maruncz** [comment]
yes that is my commit
