### ISSUE TITLE
Questions about building qGMMREG plugin

### ISSUE THREAD

**Issue by nine7nine** [cloudcompare/trunk#442]
Hey CC,

I'm interested in getting the qMMREG plugin on Archlinux, but so far I haven't had any luck.  Archlinux doesn't package VXL, but I have went ahead and installed it / packaged it too. 

However, I am still finding that CC isn't finding the needed header file(s) here;

/home/ninez/github/TEMP/cloudcompare_ICC-git/src/trunk/plugins/qGMMREG/GMMREG/C++/gmmreg_base.h(11): catastrophic error: cannot open source file "vnl/vnl_vector.h"
  #include <vnl/vnl_vector.h>
                             ^
more detail on plugin failure; http://pastebin.com/g4KEb0Cd

the includes for vxl are located at; 

/usr/include/vxl 
/usr/include/vxl/core

... and the (apparent) missing header file can be found here;

/usr/include/vxl/core/vnl/vnl_vector.h

cmake seems to find the VXL_DIR / cmake file, but the compile fails / not finding the needed header file(s)... I haven't been able to get any further in building the plugin, beyond that... Are there other parameters/flags for CC/cmake that might help? ...

I think that I have packaged VXL properly and it _should_ be good.

**Comment by cloudcompare** [comment]
The qGMMREG plugin was an experiment and it was quite disappointing (because of the results and the fact that it's very slow). I don't intend to ship it in future versions of CC.

On my side I just have to compile VXL (the only BUILD option checked in CMake is 'BUILD_CORE_NUMERICS'). No other options / dependencies are set.

And then I only provide the 'build' directory to the plugin (VXL_DIR).

**Comment by nine7nine** [comment]
hey CC,

ah, okay. if it's not intended for future versions, then I won't bother trying to get it running. So that's good to know. thanks!
